### ISSUE TITLE
rdopkg rebase crashes on a tag

### ISSUE THREAD

**Issue by ktdreyer** [redhat-openstack/rdopkg#23]
I incorrectly used `rdopkg rebase` instead of `rdopkg new-version`, and rdopkg crashed on me:

```
$ rdopkg rebase v0.94.2
## get_package_env
## ensure_patches_branch
## reset_patches_branch
git update-ref refs/heads/ceph-1.3-rhel-patches refs/remotes/patches/ceph-1.3-rhel-patches
## rebase_nightly
Rebasing upstream v0.94.2
git branch -f tmp-v0.94.2 v0.94.2
git branch -f tmp-ceph-1.3-rhel-patches ceph-1.3-rhel-patches
git checkout tmp-v0.94.2
Traceback (most recent call last):
  File "/usr/bin/rdopkg", line 9, in <module>
    load_entry_point('rdopkg==0.29.1', 'console_scripts', 'rdopkg')()
  File "/usr/lib/python2.7/site-packages/rdopkg/shell.py", line 94, in main
    runner.engage()
  File "/usr/lib/python2.7/site-packages/rdopkg/core.py", line 172, in engage
    new_args = self.action_manager.run_action(step, self.args)
  File "/usr/lib/python2.7/site-packages/rdopkg/action.py", line 155, in run_action
    return action_fun(*fun_args)
  File "/usr/lib/python2.7/site-packages/rdopkg/actions.py", line 1043, in rebase_nightly
    distgit_branch=branch)
  File "/usr/lib/python2.7/site-packages/rdopkg/actionmods/nightly.py", line 45, in rebase_nightly
    git.linearize(stable_tag)
  File "/usr/lib/python2.7/site-packages/rdopkg/utils/cmd.py", line 224, in linearize
    self('rebase', starting_point)
  File "/usr/lib/python2.7/site-packages/rdopkg/utils/cmd.py", line 102, in __call__
    return run(self.command, *params, **kwargs)
  File "/usr/lib/python2.7/site-packages/rdopkg/utils/cmd.py", line 43, in run
    cmd_str = ' '.join(cmd)
TypeError: sequence item 2: expected string, NoneType found
```

Can we make the user experience nicer? A couple of things I could think of:

1. Don't stacktrace
2. If "rebase" is not supposed to take a tag, we should probably validate that it's argument is not a tag (and then recommend "new-version" to noob users like me?)
3. Cleanup the tmp branch?

**Comment by yac** [comment]
So `rdopkg rebase` is a result of Vladan's work before he rage quit and it wasn't really tested/used much. TBH it wasn't used at all... I wonder what to do with this to avoid confusion as `rdopkg` and `git` are often used together, it's pretty likely someone will hit this by accident and then be confused.

I guess we can remove this code and leave in the git history, should the need arise. Or just rename it to something obscure? What do you think?

**Comment by apevec** [comment]
+1 to remove this code, if we come back to this, it will be a clean start

**Comment by yac** [comment]
112 lines deleted and 0 added in f2c6a3b75 - the best kind of commit :)
