### ISSUE TITLE
rdopkg 0.35 fails

### ISSUE THREAD

**Issue by apevec** [redhat-openstack/rdopkg#52]
Tripleo-ci reported this after rdopkg 0.35 was released:
https://bugs.launchpad.net/tripleo/+bug/1553173

Traceback points to the code recently added my @mhuin 
in https://github.com/redhat-openstack/rdopkg/commit/2dca3bb9f1ffa12331ad2defb7c3ffd7eced4f1e

2016-03-04 12:09:21.866 | Your branch is behind 'origin/master' by 6 commits, and can be fast-forwarded.
2016-03-04 12:09:21.866 |   (use "git pull" to update your local branch)
2016-03-04 12:09:21.866 | HEAD is now at 22caed9 Merge commit 'refs/changes/79/278979/2' of ssh://review.openstack.org:29418/openstack/tripleo-heat-templates into HEAD
2016-03-04 12:09:21.867 | Switched to a new branch 'origin/master'
2016-03-04 12:09:21.872 | HEAD is now at 22caed9 Merge commit 'refs/changes/79/278979/2' of ssh://review.openstack.org:29418/openstack/tripleo-heat-templates into HEAD
2016-03-04 12:09:21.883 | Switched to a new branch 'stable/liberty'
2016-03-04 12:09:21.891 | HEAD is now at 22caed9 Merge commit 'refs/changes/79/278979/2' of ssh://review.openstack.org:29418/openstack/tripleo-heat-templates into HEAD
2016-03-04 12:09:21.899 | Switched to a new branch 'origin/stable/liberty'
2016-03-04 12:09:21.910 | HEAD is now at 22caed9 Merge commit 'refs/changes/79/278979/2' of ssh://review.openstack.org:29418/openstack/tripleo-heat-templates into HEAD
2016-03-04 12:09:21.915 | /opt/stack/new/delorean /opt/stack/new/tripleo-ci
2016-03-04 12:09:22.355 | Traceback (most recent call last):
2016-03-04 12:09:22.356 |   File "./venv/bin/delorean", line 10, in <module>
2016-03-04 12:09:22.356 |     sys.exit(main())
2016-03-04 12:09:22.356 |   File "/opt/stack/new/delorean/venv/lib/python2.7/site-packages/delorean/shell.py", line 137, in main
2016-03-04 12:09:22.357 |     tags=cp.get("DEFAULT", "tags"))
2016-03-04 12:09:22.357 |   File "/opt/stack/new/delorean/venv/lib/python2.7/site-packages/delorean/shell.py", line 351, in getpackages
2016-03-04 12:09:22.357 |     apply_tag=tags)
2016-03-04 12:09:22.398 |   File "/opt/stack/new/delorean/venv/lib/python2.7/site-packages/rdopkg/actionmods/rdoinfo.py", line 45, in __init__
2016-03-04 12:09:22.398 |     repoman.RepoManager.__init__(self, *args, **kwargs)
2016-03-04 12:09:22.399 |   File "/opt/stack/new/delorean/venv/lib/python2.7/site-packages/rdopkg/repoman.py", line 34, in __init__
2016-03-04 12:09:22.399 |     if self.url.startswith('ssh://'):
2016-03-04 12:09:22.400 | AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by apevec** [comment]
Fixed in https://github.com/redhat-openstack/rdopkg/commit/53494133437f289ca9d0bf0af0ed74cccfea0015
